services:
    db:
        platform: linux/amd64
        image: mysql:8.0.26
        container_name: 'mysql'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mysql_test_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: secret
            TZ: 'Asia/Tokyo'
        ports:
            - 4306:3306
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - db_data:/var/lib/mysql
            - db_my.cnf:/etc/mysql/conf.d/my.cnf
            - db_sql:/docker-entrypoint-initdb.d

    php:
        build: ./docker/php
        container_name: 'php-fpm'
        volumes:
            - ./api:/var/www

    nginx:
        image: nginx:latest
        container_name: 'nginx'
        ports:
            - 8000:80
        volumes:
            - ./api:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    phpmyadmin:
        platform: linux/amd64
        image: phpmyadmin/phpmyadmin:latest
        container_name: 'phpmyadmin'
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
            - PMA_USER=admin
            - PMA_PASSWORD=secret
        links:
            - db
        ports:
            - 8081:80
        volumes:
            - ./phpmyadmin/sessions:/sessions

    mail:
        platform: linux/amd64
        image: mailhog/mailhog
        container_name: 'mailhog'
        ports:
            - 8025:8025

volumes:
    db_data:
    db_my.cnf:
    db_sql:
